development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: redis://localhost:6379/1

# development: &development
#   :url: redis://localhost:6379
#   :host: localhost
#   :port: 6379
#   :timeout: 1
#   :inline: true

# test: *development

production: &production
  :url:     redis://h:p5a59816abaefc05122d33d86d54469392df5e7ef079271c34a5abba0b06a14a5@ec2-52-4-142-124.compute-1.amazonaws.com:6839
  :host: guest-user-chat.herokuapp.com
  :port: 49382
  :password: p5a59816abaefc05122d33d86d54469392df5e7ef079271c34a5abba0b06a14a5
  :inline: true
  :timeout: 1